[package]
name = "armillae-llm"
version.workspace = true
edition.workspace = true

[features]
mock = []

[dependencies]
armillae-core = { version = "0.1.0-alpha.0", path = "../armillae-core" }
futures-util = "0.3"
secrecy = "0.10"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "2"
toml = "0.9"
url = { version = "2", features = ["serde"] }

[dev-dependencies]
futures-executor = "0.3"
